import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal/LegalPage";

export default function PrivacyPage() {
  const subheading = (text: string) => (
    <div className="mt-5 text-sm font-semibold text-white/85">{text}</div>
  );

  const sections: LegalSection[] = [
    {
      title: "Introduction",
      body: (
        <>
          <p>Welcome to Commenter AI</p>
          <p className="mt-3">
            MConsultants LTD (&quot;us&quot;, &quot;we&quot;, or
            &quot;our&quot;) operates https://commenter.ai (hereinafter referred
            to as &quot;Service&quot;).
          </p>
          <p className="mt-3">
            Our Privacy Policy governs your visit to https://commenter.ai and
            explains how we collect, safeguard and disclose information that
            results from your use of our Service.
          </p>
          <p className="mt-3">
            We use your data to provide and improve Service. By using Service,
            you agree to the collection and use of information in accordance
            with this policy. Unless otherwise defined in this Privacy Policy,
            the terms used in this Privacy Policy have the same meanings as in
            our Terms and Conditions.
          </p>
          <p className="mt-3">
            Our Terms and Conditions (&quot;Terms&quot;) govern all use of our
            Service and together with the Privacy Policy constitutes your
            agreement with us (&quot;agreement&quot;).
          </p>
        </>
      ),
    },
    {
      title: "Definitions",
      body: (
        <>
          <p>
            SERVICE means the https://commenter.ai website is operated by
            MConsultants LTD.
          </p>
          <p className="mt-3">
            PERSONAL DATA means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
          </p>
          <p className="mt-3">
            USAGE DATA is data collected automatically either generated by the
            use of Service or from Service infrastructure itself (for example,
            the duration of a page visit). COOKIES are small files stored on
            your device (computer or mobile device).
          </p>
          <p className="mt-3">
            DATA CONTROLLER means a natural or legal person who (either alone or
            jointly or in common with other persons) determines the purposes for
            which and the manner in which any personal data are, or are to be,
            processed. For the purpose of this Privacy Policy, we are a Data
            Controller of your data.
          </p>
          <p className="mt-3">
            DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal
            person who processes the data on behalf of the Data Controller. We
            may use the services of various Service Providers in order to
            process your data more effectively.
          </p>
          <p className="mt-3">
            DATA SUBJECT is any living individual who is the subject of Personal
            Data.
          </p>
          <p className="mt-3">
            THE USER is the individual using our Service. The User corresponds
            to the Data Subject, who is the subject of Personal Data.
          </p>
        </>
      ),
    },
    {
      title: "Information Collection and Use",
      body: (
        <p>
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </p>
      ),
    },
    {
      title: "Types of Data Collected",
      body: (
        <>
          {subheading("Personal Data")}
          <p className="mt-3">
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you (&quot;Personal Data&quot;). Personally identifiable
            information may include, but is not limited to:
          </p>
          <p className="mt-3">(a) Email address</p>
          <p className="mt-3">(b) Cookies and Usage Data</p>
          <p className="mt-3">
            We may use your Personal Data to contact you with newsletters,
            marketing or promotional materials and other information that may be
            of interest to you. You may opt out of receiving any, or all, of
            these communications from us by following the unsubscribe link.
          </p>

          {subheading("Usage Data")}
          <p className="mt-3">
            We may also collect information that your browser sends whenever you
            visit our Service or when you access Service by or through a mobile
            device (&quot;Usage Data&quot;).
          </p>
          <p className="mt-3">
            This Usage Data may include information such as your computer&apos;s
            Internet Protocol address (e.g. IP address), browser type, browser
            version, the pages of our Service that you visit, the time and date
            of your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data.
          </p>
          <p className="mt-3">
            When you access Service with a mobile device, this Usage Data may
            include information such as the type of mobile device you use, your
            mobile device unique ID, the IP address of your mobile device, your
            mobile operating system, the type of mobile Internet browser you
            use, unique device identifiers and other diagnostic data.
          </p>

          {subheading("Tracking Cookies Data")}
          <p className="mt-3">
            We use cookies and similar tracking technologies to track the
            activity on our Service and we hold certain information.
          </p>
          <p className="mt-3">
            Cookies are files with a small amount of data which may include an
            anonymous unique identifier. Cookies are sent to your browser from a
            website and stored on your device. Other tracking technologies are
            also used such as beacons, tags and scripts to collect and track
            information and to improve and analyze our Service.
          </p>
          <p className="mt-3">
            You can instruct your browser to refuse all cookies or to indicate
            when a cookie is being sent. However, if you do not accept cookies,
            you may not be able to use some portions of our Service.
          </p>
          <p className="mt-3">Examples of Cookies we use:</p>
          <p className="mt-3">
            (a) Session Cookies: We use Session Cookies to operate our Service.
          </p>
          <p className="mt-3">
            (b) Preference Cookies: We use Preference Cookies to remember your
            preferences and various settings.
          </p>
          <p className="mt-3">
            (c) Security Cookies: We use Security Cookies for security purposes.
          </p>
          <p className="mt-3">
            (d) Advertising Cookies: Advertising Cookies are used to serve you
            with advertisements that may be relevant to you and your interests.
          </p>

          {subheading("Other Data")}
          <p className="mt-3">
            While using our Service, we may also collect the following
            information: sex, age, date of birth, place of birth, passport
            details, citizenship, registration at place of residence and actual
            address, telephone number (work, mobile), details of documents on
            education, qualification, professional training, employment
            agreements, non-disclosure agreements, information on bonuses and
            compensation, information on marital status, family members, social
            security (or taxpayer identificatio number, office location and
            other data.
          </p>

          {subheading("Mobile App Data")}
          <p className="mt-3">
            If you use our mobile application, we may collect:
          </p>
          <p className="mt-3">
            (a) Session Tokens: Stored locally on your device to maintain login
            sessions. Tokens are encrypted, automatically expire after 7 days,
            and are not shared with any third party.
          </p>
          <p className="mt-3">
            (b) Post &amp; Comment Data: Posts, comments, and engagement
            metadata (such as reactions and applied filters) are securely
            fetched through our backend APIs from your connected professional
            network account.
          </p>
          <p className="mt-3">
            (c) Al-Based Comment Generation: When you choose to generate a
            comment, only the relevant post text and your preferred tone are
            sent to our secure backend. The backend processes this data using
            third-party Al services to generate a suggested comment. No personal
            identifiers or account credentials are shared in this process.
          </p>

          {subheading("Report Data")}
          <p className="mt-3">
            If you choose to report Al-generated content within the mobile app,
            we may collect the following information solely for moderation and
            improvement purposes: The Al-generated comment or content being
            reported The reason or category selected for reporting A timestamp
            of when the report was submitted Non-identifiable metadata such as
            device type or session ID (no personal identifiers are collected
            unless already part of the session token) This data is not linked to
            your personal identity and is used exclusively to review flagged
            content and improve future comment quality. It is not shared with
            any third parties.
          </p>
        </>
      ),
    },
    {
      title: "Use of Data",
      body: (
        <>
          <p>MConsultants LTD uses the collected data for various purposes:</p>
          <p className="mt-3">(a) to provide and maintain our Service;</p>
          <p className="mt-3">
            (b) to notify you about changes to our Service;
          </p>
          <p className="mt-3">
            (c) to allow you to participate in interactive features of our
            Service when you choose to do so;
          </p>
          <p className="mt-3">(d) to provide customer support;</p>
          <p className="mt-3">
            (e) to gather analysis or valuable information so that we can
            improve our Service;
          </p>
          <p className="mt-3">(f) to monitor the usage of our Service;</p>
          <p className="mt-3">
            (g) to detect, prevent and address technical issues;
          </p>
          <p className="mt-3">
            (h) to fulfill any other purpose for which you provide it;
          </p>
          <p className="mt-3">
            (i) to carry out our obligations and enforce our rights arising from
            any contracts entered into between you and us, including for billing
            and collection;
          </p>
          <p className="mt-3">
            (j) to provide you with notices about your account and/or
            subscription, including expiration and renewal notices,
            email-instructions, etc.;
          </p>
          <p className="mt-3">
            (k) to provide you with news, special offers and general information
            about other goods, services and events which we offer that are
            similar to those that you have already purchased or enquired about
            unless you have opted not to receive such information;
          </p>
          <p className="mt-3">
            (I) in any other way we may describe when you provide t information;
          </p>
          <p className="mt-3">(m) for any other purpose with your consent;</p>
          <p className="mt-3">(n) no Third-Party Sharing;</p>
          <p className="mt-3">
            (o) we do not sell, rent, or share your personal data with third
            parties for marketing or advertising purposes. All post, comment,
            and Al-related processing is performed securely via our backend APIs
            and is only used to provide app functionality;
          </p>
          <p className="mt-3">
            (p) to process, investigate, and improve the quality of Al-generated
            content based on user-submitted reports, while ensuring the
            anonymity of the reporting user.
          </p>
        </>
      ),
    },
    {
      title: "Retention of Data",
      body: (
        <p>
          We will retain your Personal Data only for as long as is necessary for
          the purposes set out in this Privacy Policy. We will retain and use
          your Personal Data to the extent necessary to comply with our legal
          obligations (for example, if we are required to retain your data to
          comply with applicable laws), resolve disputes, and enforce our legal
          agreements and policies. We will also retain Usage Data for internal
          analysis purposes. Usage Data is generally retained for a shorter
          period, except when this data is used to strengthen the security or to
          improve the functionality of our Service, or we are legally obligated
          to retain this data for longer time periods.
        </p>
      ),
    },
    {
      title: "Transfer of Data",
      body: (
        <>
          <p>
            Your information, including Personal Data, may be transferred to and
            maintained on - computers located outside of your state, province,
            country or other governmental jurisdiction where the data protection
            laws may differ from those of your jurisdiction.
          </p>
          <p className="mt-3">
            If you are located outside United States and choose to provide
            information to us, please note that we transfer the data, including
            Personal Data, to United States and process it there. Your consent
            to this Privacy Policy followed by your submission of such
            information represents your agreement to that transfer.
          </p>
          <p className="mt-3">
            MConsultants LTD will take all the steps reasonably necessary to
            ensure that your data is treated securely and in accordance with
            this Privacy Policy and no transfer of your Personal Data will take
            place to an organisation or a country unless there are adequate
            controls in place including the security of your data and other
            personal information.
          </p>
        </>
      ),
    },
    {
      title: "Disclosure of Data",
      body: (
        <>
          <p>
            We may disclose personal information that we collect, or you
            provide:
          </p>
          <p className="mt-3">
            (a) Disclosure for Law Enforcement. Under certain circumstances, we
            may be required to disclose your Personal Data if required to do so
            by law or in response to valid requests by public authorities.
          </p>
          <p className="mt-3">
            (b) Business Transaction. If we or our subsidiaries are involved in
            a merger, acquisition or asset sale, your Personal Data may be
            transferred.
          </p>
          <p className="mt-3">
            (c) Other cases. We may disclose your information also:
          </p>
          <p className="mt-3">(i) to our subsidiaries and affiliates;</p>
          <p className="mt-3">
            (ii) to contractors, service providers, and other third parties we
            use to support our business;
          </p>
          <p className="mt-3">
            (iii) to fulfill the purpose for which you provide it;
          </p>
          <p className="mt-3">
            (iv) for any other purpose disclosed by us when you provide the
            information;
          </p>
        </>
      ),
    },
    {
      title: "Security of Data",
      body: (
        <p>
          The security of your data is important to us but remember that no
          method of transmission over the Internet or method of electronic
          storage is 100% secure. While we strive to use commercially acceptable
          means to protect your Personal Data, we cannot guarantee its absolute
          security.
        </p>
      ),
    },
    {
      title:
        "Your Data Protection Rights Under General Data Protection Regulation (GDPR)",
      body: (
        <>
          <p>
            If you are a resident of the European Union (EU) and European
            Economic Area (EEA), you have certain data protection rights,
            covered by GDPR. - See more at https://eur-lex.europa.eu/
            eli/reg/2016/679/oj
          </p>
          <p className="mt-3">
            We aim to take reasonable steps to allow you to correct, amend,
            delete, or limit the use of your Personal Data.
          </p>
          <p className="mt-3">
            If you wish to be informed what Personal Data we hold about you and
            if you want it to be removed from our systems, please email us at
            support@commenter.ai.
          </p>
          <p className="mt-3">
            In certain circumstances, you have the following data protection
            rights:
          </p>
          <p className="mt-3">
            (a) the right to access, update or to delete the information we have
            on you;
          </p>
          <p className="mt-3">
            (b) the right of rectification. You have the right to have your
            information rectified if that information is inaccurate or
            incomplete;
          </p>
          <p className="mt-3">
            (c) the right to object. You have the right to object to our
            processing of your Personal Data;
          </p>
          <p className="mt-3">
            (d) the right of restriction. You have the right to request that we
            restrict the processing of your personal information;
          </p>
          <p className="mt-3">
            (e) the right to data portability. You have the right to be provided
            with a copy of your Personal Data in a structured, machine-readable
            and commonly used format;
          </p>
          <p className="mt-3">
            (f) the right to withdraw consent. You also have the right to
            withdraw your consent at any time where we rely on your consent to
            process your personal information; Please note that we may ask you
            to verify your identity before responding to such requests. Please
            note, we may not able to provide Service without some necessary
            data. You have the right to complain to a Data Protection Authority
            about our collection and use of your Personal Data. For more
            information, please contact your local data protection authority in
            the European Economic Area (EEA).
          </p>
          <p className="mt-3">
            Mobile app users your mobile session data is stored only locally on
            your device and automatically expires after 7 days. To continue
            using the app, you must scan a new QR code after expiration. You may
            request complete data deletion, including any data processed via our
            backend, by contacting us at support@commenter.ai.
          </p>
        </>
      ),
    },
    {
      title:
        "Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)",
      body: (
        <>
          <p>
            CalOPPA is the first state law in the nation to require commercial
            websites and online services to post a privacy policy. The
            law&apos;s reach stretches well beyond California to require a
            person or company in the United States (and conceivable the world)
            that operates websites collecting personally identifiable
            information from California consumers to post a conspicuous privacy
            policy on its website stating exactly the information being being
            collected and those individuals with whom it is being shared, and to
            comply with this policy. – See more at:
            https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/
          </p>
          <p className="mt-3">
            According to CalOPPA we agree to the following:
          </p>
          <p className="mt-3">(a) users can visit our site anonymously;</p>
          <p className="mt-3">
            (b) our Privacy Policy link includes the word &quot;Privacy&quot;,
            and can easily be found on the page specified above on the home page
            of our website;
          </p>
          <p className="mt-3">
            (c) users will be notified of any privacy policy changes on our
            Privacy Policy Page;
          </p>
          <p className="mt-3">
            (d) users are able to change their personal information by emailing
            us at support@commenter.ai.
          </p>

          <p className="mt-5 font-semibold text-white/85">
            Our Policy on &quot;Do Not Track&quot; Signals:
          </p>
          <p className="mt-3">
            We honor Do Not Track signals and do not track, plant cookies, or
            use advertising when a Do Not Track browser mechanism is in place.
            Do Not Track is a preference you can set in your web browser to
            inform websites that you do not want to be tracked.
          </p>
          <p className="mt-3">
            You can enable or disable Do Not Track by visiting the Preferences
            or Settings page of your web browser.
          </p>
        </>
      ),
    },
    {
      title:
        "Your Data Protection Rights under the California Consumer Privacy Act (CCPA)",
      body: (
        <>
          <p>
            If you are a California resident, you are entitled to learn what
            data we collect about you, ask to delete your data and not to sell
            (share) it. To exercise your data protection rights, you can make
            certain requests and ask us:
          </p>
          <p className="mt-3">
            (a) What personal information we have about you. If you make this
            request, we will return to you:
          </p>
          <p className="mt-3">
            (i) The categories of personal information we have collected about
            you.
          </p>
          <p className="mt-3">
            (ii) The categories of sources from which we collect your personal
            information.
          </p>
          <p className="mt-3">
            (iii) The business or commercial purpose for collecting or selling
            your personal information.
          </p>
          <p className="mt-3">
            (iv) The categories of third parties with whom we share personal
            information.
          </p>
          <p className="mt-3">
            (v) The specific pieces of personal information we have collected
            about you.
          </p>
          <p className="mt-3">
            (vi) A list of categories of personal information that we have sold,
            along with the category of any other company we sold it to. If we
            have not sold your personal information, we will inform you of that
            fact.
          </p>
          <p className="mt-3">
            (vii) A list of categories of personal information that we have
            disclosed for a business purpose, along with the category of any
            other company we shared it with.
          </p>
          <p className="mt-3">
            Please note, you are entitled to ask us to provide you with this
            information up to two times in a rolling twelve-month period. When
            you make this request, the information provided may be limited to
            the personal information we collected about you in the previous 12
            months.
          </p>
          <p className="mt-3">
            (b) To delete your personal information. If you make this request,
            we will delete the personal information we hold about you as of the
            date of your request from our records and direct any service
            providers to do the same. In some cases, deletion may be
            accomplished through de-identification of the information. If you
            choose to delete your personal information, you may not be able to
            use certain functions that require your personal information to
            operate.
          </p>
          <p className="mt-3">
            (c) To stop selling your personal information. We do not sell your
            personal information for monetary consideration. However, under some
            circumstances, a transfer of personal information to a third party,
            or within our family of companies, without monetary consideration
            may be considered a &quot;sale&quot; under California law.
          </p>
          <p className="mt-3">
            If you submit a request to stop selling your personal information,
            we will stop making such transfers. If you are a California
            resident, to opt-out of the sale of your personal information, click
            &quot;Do Not Sell My Personal Information&quot; at the bottom of our
            home page to submit your request.
          </p>
          <p className="mt-3">
            Please note, if you ask us to delete or stop selling your data, it
            may impact your experience with us, and you may not be able to
            participate in certain programs or membership services which require
            the usage of your personal information to function. But in no
            circumstances, we will discriminate against you for exercising your
            rights.
          </p>
          <p className="mt-3">
            To exercise your California data protection rights described above,
            please send your request(s) by one of the following means:
          </p>
          <p className="mt-3">By email: support@commenter.ai</p>
          <p className="mt-3">
            Your data protection rights, described above, are covered by the
            CCPA, short for the California Consumer Privacy Act. To find out
            more, visit the official California Legislative Information website.
            The CCPA took effect on 01/01/2020.
          </p>
        </>
      ),
    },
    {
      title: "Service Providers",
      body: (
        <>
          <p>
            We may employ third-party companies and individuals to facilitate
            our Service (&quot;Service Providers&quot;), provide Service on our
            behalf, perform Service-related services, or assist us in analyzing
            how our Service is used.
          </p>
          <p className="mt-3">
            These third parties have access to your Personal Data only to
            perform these tasks on our behalf and are obligated not to disclose
            or use it for any other purpose.
          </p>
          <p className="mt-3">
            For mobile services, we use secure backend APIs that may interact
            with third-party services to fetch posts and generate Al-powered
            comments. These third-party services act strictly as data processors
            and do not store or reuse your data for any other purpose.
          </p>
        </>
      ),
    },
    {
      title: "Analytics",
      body: (
        <p>
          We may use third-party Service Providers to monitor and analyze the
          use of https://commenter.ai.
        </p>
      ),
    },
    {
      title: "Footer / Legal Notices",
      body: (
        <>
          <p>
            Commenter AI is not affiliated, associated, authorized, endorsed by,
            or in any way officially connected with the LinkedIn™ Corporation,
            registered in the U.S. and other countries. LinkedIn™ is a trademark
            of the LinkedIn™ Corporation.
          </p>
          <p className="mt-3">© 2025 Commenter AI. All rights reserved.</p>
          <p className="mt-3">
            Learn · Pricing · Blog · Features · Guide · Billing/Trust · How It
            Works
          </p>
          <p className="mt-3">
            Company · About Us · Contact Us · Become a Partner
          </p>
          <p className="mt-3">Privacy Policy · Terms of Services</p>
        </>
      ),
    },
  ];

  return (
    <LegalPage
      title="Privacy Policy"
      updatedAt="February 4, 2026"
      variant="plain"
      sections={sections}
    />
  );
}

export const metadata: Metadata = {
  title: "Privacy Policy",
};
