import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal/LegalPage";

export default function PrivacyPage() {
  const subheading = (text: string) => (
    <div className="mt-5 text-sm font-semibold text-white/85">{text}</div>
  );
  const paragraph = (text: string) => <p className="mt-3">{text}</p>;

  const sections: LegalSection[] = [
    {
      title: "Introduction",
      body: (
        <>
          <p>Welcome to Commenter.ai</p>
          <p className="mt-3">
            MConsultants LTD (“us”, “we”, or “our”) operates https://commenter.ai
            (hereinafter referred to as “Service”).
          </p>
          <p className="mt-3">
            Our Privacy Policy governs your visit to https://commenter.ai and
            explains how we collect, safeguard and disclose information that
            results from your use of our Service.
          </p>
          <p className="mt-3">
            We use your data to provide and improve Service. By using Service,
            you agree to the collection and use of information in accordance
            with this policy. Unless otherwise defined in this Privacy Policy,
            the terms used in this Privacy Policy have the same meanings as in
            our Terms and Conditions.
          </p>
          <p className="mt-3">
            Our Terms and Conditions (“Terms”) govern all use of our Service and
            together with the Privacy Policy constitutes your agreement with us
            (“agreement”).
          </p>
        </>
      ),
    },
    {
      title: "Definitions",
      body: (
        <>
          <p>
            SERVICE means the https://commenter.ai website is operated by
            MConsultants LTD.
          </p>
          <p className="mt-3">
            PERSONAL DATA means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
          </p>
          <p className="mt-3">
            USAGE DATA is data collected automatically either generated by the
            use of Service or from Service infrastructure itself (for example,
            the duration of a page visit).
          </p>
          <p className="mt-3">
            COOKIES are small files stored on your device (computer or mobile
            device).
          </p>
          <p className="mt-3">
            DATA CONTROLLER means a natural or legal person who (either alone or
            jointly or in common with other persons) determines the purposes for
            which and the manner in which any personal data are, or are to be,
            processed. For the purpose of this Privacy Policy, we are a Data
            Controller of your data.
          </p>
          <p className="mt-3">
            DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal
            person who processes the data on behalf of the Data Controller. We
            may use the services of various Service Providers in order to
            process your data more effectively.
          </p>
          <p className="mt-3">
            DATA SUBJECT is any living individual who is the subject of Personal
            Data.
          </p>
          <p className="mt-3">
            THE USER is the individual using our Service. The User corresponds
            to the Data Subject, who is the subject of Personal Data.
          </p>
        </>
      ),
    },
    {
      title: "Information collected and used",
      body: (
        <p>
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </p>
      ),
    },
    {
      title: "Types of Data Collected",
      body: (
        <>
          {subheading("Personal Data")}
          <p className="mt-3">
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you (“Personal Data”). Personally identifiable information
            may include, but is not limited to:
          </p>
          <p className="mt-3">(a) Email address</p>
          <p className="mt-3">(b) Cookies and Usage Data</p>
          <p className="mt-3">
            We may use your Personal Data to contact you with newsletters,
            marketing or promotional materials and other information that may be
            of interest to you. You may opt out of receiving any, or all, of
            these communications from us by following the unsubscribe link.
          </p>

          {subheading("Usage Data")}
          <p className="mt-3">
            We may also collect information that your browser sends whenever you
            visit our Service or when you access Service by or through a mobile
            device (“Usage Data”).
          </p>
          <p className="mt-3">
            This Usage Data may include information such as your computer’s
            Internet Protocol address (e.g. IP address), browser type, browser
            version, the pages of our Service that you visit, the time and date
            of your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data.
          </p>
          <p className="mt-3">
            When you access Service with a mobile device, this Usage Data may
            include information such as the type of mobile device you use, your
            mobile device unique ID, the IP address of your mobile device, your
            mobile operating system, the type of mobile Internet browser you
            use, unique device identifiers and other diagnostic data.
          </p>

          {subheading("Tracking Cookies Data")}
          <p className="mt-3">
            We use cookies and similar tracking technologies to track the
            activity on our Service and we hold certain information.
          </p>
          <p className="mt-3">
            Cookies are files with a small amount of data which may include an
            anonymous unique identifier. Cookies are sent to your browser from a
            website and stored on your device. Other tracking technologies are
            also used such as beacons, tags and scripts to collect and track
            information and to improve and analyze our Service.
          </p>
          <p className="mt-3">
            You can instruct your browser to refuse all cookies or to indicate
            when a cookie is being sent. However, if you do not accept cookies,
            you may not be able to use some portions of our Service.
          </p>
          <p className="mt-3">Examples of Cookies we use:</p>
          <p className="mt-3">
            (a) Session Cookies: We use Session Cookies to operate our Service.
          </p>
          <p className="mt-3">
            (b) Preference Cookies: We use Preference Cookies to remember your
            preferences and various settings.
          </p>
          <p className="mt-3">
            (c) Security Cookies: We use Security Cookies for security purposes.
          </p>
          <p className="mt-3">
            (d) Advertising Cookies: Advertising Cookies are used to serve you
            with advertisements that may be relevant to you and your interests.
          </p>

          {subheading("Other Data")}
          <p className="mt-3">
            While using our Service, we may also collect the following
            information: sex, age, date of birth, place of birth, passport
            details, citizenship, registration place of residence and actual
            address, telephone number (work, mobile), details of documents on
            education, qualification, professional training, employment
            agreements, non-disclosure agreements, information on bonuses and
            compensation, information on marital status, family members, social
            security (or other taxpayer identification) number, office location
            and other data.
          </p>

          {subheading("Mobile App Data")}
          <p className="mt-3">If you use our mobile application, we may collect:</p>
          <p className="mt-3">
            (a) Session Tokens: Stored locally on your device to maintain login
            sessions. Tokens are encrypted, automatically expire after 7 days,
            and are not shared with any third party.
          </p>
          <p className="mt-3">
            (b) Post &amp; Comment Data: Posts, comments, and engagement metadata
            (such as reactions and applied filters) are securely fetched through
            our backend APIs from your connected professional network account.
          </p>
          <p className="mt-3">
            (c) AI-Based Comment Generation: When you choose to generate a
            comment, only the relevant post text and your preferred tone are
            sent to our secure backend. The backend processes this data using
            third-party AI services to generate a suggested comment. No personal
            identifiers or account credentials are shared in this process.
          </p>

          {subheading("Report Data")}
          <p className="mt-3">
            If you choose to report AI-generated content within the mobile app,
            we may collect the following information solely for moderation and
            improvement purposes: The AI-generated comment or content being
            reported The reason or category selected for reporting A timestamp
            of when the report was submitted Non-identifiable metadata such as
            device type or session ID (no personal identifiers are collected
            unless already part of the session token) This data is not linked to
            your personal identity and is used exclusively to review flagged
            content and improve future comment quality. It is not shared with
            any third parties.
          </p>
        </>
      ),
    },
    {
      title: "Use of data",
      body: (
        <>
          <p>We use information to:</p>
          <ul className="mt-3 list-disc space-y-2 pl-5">
            <li>Provide and maintain the Service</li>
            <li>Authenticate users and prevent fraud</li>
            <li>Process payments and manage subscriptions</li>
            <li>Improve performance, reliability, and user experience</li>
            <li>Send service messages and (where permitted) marketing</li>
          </ul>
          {subheading("Legal bases (where applicable)")}
          {paragraph(
            "Where required, we process Personal Data based on contract necessity, legitimate interests, consent, and/or compliance with legal obligations.",
          )}
          {subheading("Legitimate interests")}
          {paragraph(
            "Examples include maintaining security, preventing abuse, and improving the Service. We balance these interests against your rights and expectations.",
          )}
        </>
      ),
    },
    {
      title: "Retention of data",
      body: (
        <>
          <p>
            We retain Personal Data only for as long as necessary to provide the
            Service and for legitimate and essential business purposes, such as
            maintaining performance, complying with legal obligations, resolving
            disputes, and enforcing agreements.
          </p>
          {paragraph(
            "Retention periods depend on the type of data, why we need it, and applicable legal requirements.",
          )}
        </>
      ),
    },
    {
      title: "Cookies and tracking technologies",
      body: (
        <>
          <p>
            We use cookies and similar technologies to operate and improve the
            Service. Cookies are small files stored on your device.
          </p>
          {subheading("Types of cookies")}
          <ul className="mt-3 list-disc space-y-2 pl-5">
            <li>
              <span className="font-semibold text-white/85">Necessary:</span>{" "}
              required for core functionality and security.
            </li>
            <li>
              <span className="font-semibold text-white/85">Preferences:</span>{" "}
              remember choices and settings.
            </li>
            <li>
              <span className="font-semibold text-white/85">Analytics:</span>{" "}
              help us understand usage and improve the product.
            </li>
          </ul>
          {subheading("Your choices")}
          {paragraph(
            "Most browsers let you remove or reject cookies. If you block cookies, some features may not function properly.",
          )}
        </>
      ),
    },
    {
      title: "Transfer of data",
      body: (
        <>
          <p>
            Your information may be transferred to—and maintained on—systems
            located outside your jurisdiction where data protection laws may
            differ.
          </p>
          {paragraph(
            "When we transfer data internationally, we use appropriate safeguards as required by law (such as contractual protections).",
          )}
        </>
      ),
    },
    {
      title: "Disclosure of data",
      body: (
        <>
          <p>We may disclose information:</p>
          <ul className="mt-3 list-disc space-y-2 pl-5">
            <li>To vendors providing services on our behalf (processors)</li>
            <li>To comply with legal obligations or lawful requests</li>
            <li>To protect rights, safety, and security of users and the Service</li>
            <li>In connection with a merger, acquisition, or asset sale</li>
          </ul>
          {subheading("Business transfers")}
          {paragraph(
            "If we’re involved in a merger, acquisition, financing, or sale of assets, information may be transferred as part of that transaction, subject to appropriate protections.",
          )}
        </>
      ),
    },
    {
      title: "Security of data",
      body: (
        <>
          <p>
            We implement reasonable administrative, technical, and physical
            safeguards designed to protect information.
          </p>
          {paragraph(
            "However, no method of transmission or storage is completely secure. You are responsible for maintaining the confidentiality of your credentials and using a strong password.",
          )}
        </>
      ),
    },
    {
      title: "Your rights",
      body: (
        <>
          <p>
            Depending on your location, you may have rights to access, correct,
            delete, or export your data, and to object to or restrict certain
            processing.
          </p>
          <p className="mt-3">
            Contact us to exercise these rights. We may need to verify your
            identity before responding.
          </p>
          {subheading("Marketing preferences")}
          {paragraph(
            "You can opt out of marketing communications at any time by using the unsubscribe link or contacting us.",
          )}
          {subheading("Access, correction, deletion")}
          {paragraph(
            "You may request access to, correction of, or deletion of your Personal Data, subject to applicable law and certain exceptions.",
          )}
        </>
      ),
    },
    {
      title: "Service providers",
      body: (
        <p>
          We use third-party companies to support the Service (e.g., hosting,
          analytics, payment processors). They are authorized to process data
          only as needed to provide their services to us.
        </p>
      ),
    },
    {
      title: "Links to other sites",
      body: (
        <p>
          The Service may contain links to other websites. We are not
          responsible for their content or privacy practices; review their
          policies separately.
        </p>
      ),
    },
    {
      title: "Do Not Track signals",
      body: (
        <p>
          Some browsers offer a “Do Not Track” feature. There is no uniform
          standard for responding to DNT signals, so we do not currently respond
          to them.
        </p>
      ),
    },
    {
      title: "Children’s privacy",
      body: (
        <p>
          The Service is not directed to children under the age required by
          applicable law, and we do not knowingly collect Personal Data from
          children. If you believe a child has provided data to us, contact us
          and we will take appropriate steps.
        </p>
      ),
    },
    {
      title: "GDPR (EEA/UK) rights",
      body: (
        <>
          <p>
            If you are located in the European Economic Area or the United
            Kingdom, you may have rights under the GDPR, including:
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-5">
            <li>The right to access your Personal Data</li>
            <li>The right to rectify inaccurate data</li>
            <li>The right to erase data in certain circumstances</li>
            <li>The right to restrict or object to processing</li>
            <li>The right to data portability</li>
            <li>The right to withdraw consent</li>
          </ul>
          {paragraph(
            "You also have the right to lodge a complaint with your local supervisory authority.",
          )}
        </>
      ),
    },
    {
      title: "CCPA (California) notice",
      body: (
        <>
          <p>
            If you are a California resident, you may have rights under the
            California Consumer Privacy Act (CCPA/CPRA), including the right to
            know, delete, and correct certain Personal Information, and to opt
            out of certain sharing.
          </p>
          {subheading("Categories of personal information")}
          <ul className="mt-3 list-disc space-y-2 pl-5">
            <li>Identifiers (e.g., name, email, IP address)</li>
            <li>Internet or other electronic network activity</li>
            <li>Commercial information (subscription and billing metadata)</li>
          </ul>
          {subheading("Sale or sharing")}
          {paragraph(
            "We do not sell personal information as defined by the CCPA. Replace this statement if the client’s policy differs.",
          )}
        </>
      ),
    },
    {
      title: "Changes to this policy",
      body: (
        <p>
          We may update this Privacy Policy from time to time. We will post the
          updated version and revise the “Last updated” date.
        </p>
      ),
    },
    {
      title: "Contact",
      body: (
        <>
          <p>
            Questions about privacy? Contact us at{" "}
            <span className="font-semibold text-white/85">
              privacy@example.com
            </span>
            .
          </p>
          {paragraph(
            "Replace the email address and company details with the client’s real contact information.",
          )}
        </>
      ),
    },
  ];

  return (
    <LegalPage
      title="Privacy Policy"
      updatedAt="February 4, 2026"
      variant="plain"
      sections={sections}
    />
  );
}

export const metadata: Metadata = {
  title: "Privacy Policy",
};
